### ISSUE TITLE
no readme

### ISSUE THREAD

**Issue by goatandsheep** [wshager/xvfn#1]
How do I use this package? What does it do?

**Comment by wshager** [comment]
It's part of an implementation of the XQuery/XPath function suite, but it's not yet ready and will change soon. Why do you ask?

**Comment by goatandsheep** [comment]
I'm trying to figure out if I can simulate a display so I can use an
electron package for server side operation. So I wanted to try this
package.

**Comment by wshager** [comment]
Clearly this isn't an electron package. I can see how being cryptic in package names can lead to misunderstandings, therefore my apologies. FYI 'XV' stands for 'XML Virtual' (as in virtual DOM) and 'FN' stands for the hardwired namespace prefix used by the XPath function library.

**Comment by goatandsheep** [comment]
Yes but electron packages require xvfb

**Comment by wshager** [comment]
What package are you referring to?

**Comment by wshager** [comment]
Perhaps you mean Xvfb?

**Comment by goatandsheep** [comment]
it's ok! I realized I don't even need it anymore, but I also now know that this package is still in progress, so my apologies for that.

**Comment by wshager** [comment]
Thanks for making me consider another name :1st_place_medal:  
Since it's rather close to Xvfb (which deserves a better name also), that may prevent more confusion in the future.
